name: Fetch and Process Rust Skins

on:
  schedule:
    # Run every Thursday at 6:00 PM EST (UTC-5)
    - cron: '0 23 * * 4'  # 23:00 UTC = 18:00 EST, day 4 = Thursday
  workflow_dispatch:

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Fetch and process Rust skins
        run: |
          echo "Running fetch_skins.py for SCMM-only fetch"
          python scripts/fetch_skins.py
        continue-on-error: false  # Fail the workflow if the script fails
          
      - name: Commit and push changes
        run: |
          # Get current date for commit message
          CURRENT_DATE=$(date +%Y-%m-%d)
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all relevant files
          git add docs/public/data/scmm.json
          git add docs/public/data/exporter_skins-*.json
          git add docs/public/data/merged_skins.json
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Rust skins data [$CURRENT_DATE] [skip ci]"
            git push
          fi 